name: screentheme
description: Flutter plugin to change the theme (light / dark) of the status & navigation bars
version: 0.0.2
author: Edouard Marquez <moi@edouard-marquez.me>
homepage: https://github.com/g123k/flutter-screen-theme-plugin

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: fr.g123k.screentheme
    pluginClass: ScreenThemePlugin


environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.1.2 <2.0.0"